### ISSUE TITLE
[Suggestion] Calcite, Blackstone and Basalt ores

### ISSUE THREAD

**Issue by K0-RR** [AstralOrdana/Mores#2]
Basalt and Blackstone ores - Quartz and Nether Gold.
From 1.18 Calcite is more common.

**Comment by AstralOrdana** [comment]
Its an interesting suggestion but I think that the nether ores make sense in the blocks they're in already, I don't think they'd really fit.
As for Calcite ore varieties, Calcite doesn't generate outside of geodes aside from strips in stony peaks and I don't think that warrants adding eight whole new blocks as most of the ores would be impossible to generate.
