### ISSUE TITLE
Emissive Textures Support for Shaders

### ISSUE THREAD

**Issue by xdevilkillx** [AstralOrdana/Mores#3]
Ores do not support Emissive Textures in Shaders (Shaders in pictures is Complementary Shaders)
![2021-12-05_00 12 23](https://user-images.githubusercontent.com/59124323/144734577-3bb5106d-37e2-4345-b160-3c10cdb7034b.png)
![2021-12-05_00 12 42](https://user-images.githubusercontent.com/59124323/144734580-0ed2786f-0f62-4084-a8a9-216a0c38c68c.png)

**Comment by AstralOrdana** [comment]
If you can point me toward a resource that will show me how to add support for this then I will do my best to add it.

**Comment by xdevilkillx** [comment]
This seems like it: [Tutorial](https://www.youtube.com/watch?v=0f41gquV-hQ)

**Comment by AstralOrdana** [comment]
so the shader will recognize a folder called `optifine`?

**Comment by AstralOrdana** [comment]
test the version I just pushed because I don't have my game setup to test emissive textures

**Comment by xdevilkillx** [comment]
Taken from reddit:

"Long answer: An emissive texture overlays on top of any already existing in-world texture. So if you add a custom item texture (CIT) depending on the item's name, you can just make parts of that texture emissive by adding an emissive map for that item.

Example: My pack has a unique diamond_sword.png texture. I've added a custom variant for diamond swords when they're renamed to "Command Block Sword", which uses the command_block_sword.png texture in the CIT folder of my resource pack. That folder also contains a command_block_sword_emissive.png texture (where "_emissive" is specified in my pack's emissive.properties file), which applies an emissive map on top of the command_block_sword.png file - which only shows up when a diamond sword has a custom name."

So possibly just add the emissive texture to the same folder as the regular? I'm not sure.

**Comment by AstralOrdana** [comment]
yeah i figured that part out, i just don't have a way to quickly test it

**Comment by xdevilkillx** [comment]
I can test it if you'd like. If all I need to do is install it.

**Comment by AstralOrdana** [comment]
wait, i need to push a fix first

**Comment by AstralOrdana** [comment]
go to `mores/build/libs` and take the mores-1.2.5.jar file and put it in your mods folder

**Comment by xdevilkillx** [comment]
Sorry, I'm having trouble finding where that is.

**Comment by AstralOrdana** [comment]
the folder called `build` inside the main folder of the repository

**Comment by xdevilkillx** [comment]
I do not see that, do you not have it public?
![Capture](https://user-images.githubusercontent.com/59124323/144759745-b87a493a-07f5-486d-9ea4-1cb2112697da.PNG)

**Comment by AstralOrdana** [comment]
I have uploaded it to curseforge as a beta version, you can get it there

**Comment by xdevilkillx** [comment]
It is not working, though you did change it that the default redstone ores are not emissive unless glowing(mores redstone is not emissive though) Though I'd prefer if redstone is always emissive.
![2021-12-05_14 10 40](https://user-images.githubusercontent.com/59124323/144760220-5ae159e9-cb99-4997-a3d9-6c3a8a747c7d.png)
![2021-12-05_14 11 46](https://user-images.githubusercontent.com/59124323/144760222-4f8b8451-29dc-42b0-8614-003acefc237a.png)

**Comment by xdevilkillx** [comment]
To be fair I am also using Sodium+Iris Shaders and not Optifine, so I can try that in a sec.

**Comment by xdevilkillx** [comment]
I seem to be crashing when loading into world with Optifabric, so I can't test Optifine.
Though I don't see a reason why it shouldn't work with Sodium+Iris Shaders. I could be wrong though.

**Comment by AstralOrdana** [comment]
does sodium + iris shaders use the optifine system for emissive textures?

**Comment by AstralOrdana** [comment]
can't find any documentation anywhere for how to add emissive textures to iris + sodium, are you using a resource pack?

**Comment by xdevilkillx** [comment]
I'm not sure, as Complementary Shaders is what give ores Emissive properties, not resource pack.
Sodium is just another Optifine-like performance mod and Iris Shaders just enables Shaders support.

**Comment by AstralOrdana** [comment]
I know what sodium and optifine are, I just don't know where your current emissive ores are coming from so idk how to make mine do the same

**Comment by AstralOrdana** [comment]
idk if its even something I can enable on my end

**Comment by xdevilkillx** [comment]
I was just thinking that, might be up to the Complimentary Shaders Devs to do that on their end.
All well, thanks for trying anyways.

**Comment by AstralOrdana** [comment]
No worries, you might be able to ask in their discord how a mod could add emissive compatibility, if you find out any more info, feel free to create a new issue

**Comment by xdevilkillx** [comment]
According to the Discord, there's no way of adding it unless the shader natively supports it.

**Comment by K0-RR** [comment]
No, you don't need shaders for this, you can _just_ use optifine.
https://www.curseforge.com/minecraft/texture-packs/emissive-ores-1-17
https://www.planetminecraft.com/texture-pack/neon-ores-hd-1-18-emissive-ores/

**Comment by xdevilkillx** [comment]
> No, you don't need shaders for this, you can _just_ use optifine. https://www.curseforge.com/minecraft/texture-packs/emissive-ores-1-17 https://www.planetminecraft.com/texture-pack/neon-ores-hd-1-18-emissive-ores/

Yes, but neither of those affect modded ores. Shaders also add the emissive textures which again, don't affected modded ores unless implemented to do so natively.

I'm not gonna use Optifine anyways because Sodium gives me better performance, 200+FPS with shaders on, while Optifine stays around 70-80 FPS with shaders.

**Comment by K0-RR** [comment]
This is the official resource pack for BetterNether mod that adds emissive textures to mod's blocks. No idea if there is some code in the mod to make this possible.
https://www.curseforge.com/minecraft/texture-packs/lum
