### ISSUE TITLE
Using a resource pack to change the modded ores does not apply

### ISSUE THREAD

**Issue by aisukuma** [AstralOrdana/Mores#5]
I just updated from 1.2.4 to the recent version of More Ore Stones (1.2.7) and a custom resource pack that turns those ores into the classic, pre-1.16 ore textures no longer works. The top two ores are the stone and deepslate variants, the bottom four the the More Ore Stones variants. 

The custom resource pack follows the correct file path in replacing the modded textures:
**/assets/mores/textures/block**.

![2021-12-15_07 31 43](https://user-images.githubusercontent.com/22802219/146142936-44a4fa9b-f711-49ae-bb9c-23125a2c7f63.png)

**Comment by AstralOrdana** [comment]
This is an issue with the resource pack, check the file names to make sure everything matches Mores correctly.

**Comment by aisukuma** [comment]
This is the resource pack that I am currently using. I made sure that all the names are correctly matching.

[Classic Mores.zip](https://github.com/AstralOrdana/Mores-Fabric/files/7723340/Classic.Mores.zip)

**Comment by AstralOrdana** [comment]
The namespace in that resource pack is different from "mores" so its impossible for it to chance any of the Mores textures, also the names of the textures are not the names of the blocks so they wouldn't change anything even if the namespace was right.

**Comment by aisukuma** [comment]
I'm a derp. Somehow I overrided the resource pack from the custom resource pack I used for Dimensional Ores.
